apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navno-search-api
  namespace: navno
  labels:
    team: navno
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 30
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  openSearch:
    access: read
    instance: navnosearch
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: "*"
          namespace: personbruker
        - application: "*"
          namespace: navno
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
