apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navno-search-api
  namespace: personbruker
  labels:
    team: personbruker
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 15
    periodSeconds: 2
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  openSearch:
    access: read
    instance: navno-search
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: nav-dekoratoren-beta-tms
          namespace: personbruker
        - application: nav-dekoratoren-beta
          namespace: personbruker
        - application: nav-dekoratoren
          namespace: personbruker
        - application: decorator-next
          namespace: personbruker
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
