package no.nav.navnosearchapi.search.compatibility

const val FASETT_INNHOLD = "0"
const val FASETT_ENGLISH = "en"
const val FASETT_NYHETER = "1"
const val FASETT_ANALYSER_OG_FORSKNING = "5"
const val FASETT_STATISTIKK = "3"
const val FASETT_INNHOLD_FRA_FYLKER = "4"
const val FASETT_FILER = "2"

const val UNDERFASETT_INFORMASJON = "0"
const val UNDERFASETT_KONTOR = "1"
const val UNDERFASETT_SOKNAD_OG_SKJEMA = "2"

const val UNDERFASETT_PRIVATPERSON = "1"
const val UNDERFASETT_ARBEIDSGIVER = "2"
const val UNDERFASETT_STATISTIKK = "4"
const val UNDERFASETT_PRESSE = "0"
const val UNDERFASETT_PRESSEMELDINGER = "pm"
const val UNDERFASETT_NAV_OG_SAMFUNN = "5"

const val UNDERFASETT_AGDER = "0"
const val UNDERFASETT_INNLANDET = "1"
const val UNDERFASETT_MORE_OG_ROMSDAL = "2"
const val UNDERFASETT_NORDLAND = "3"
const val UNDERFASETT_OSLO = "4"
const val UNDERFASETT_ROGALAND = "5"
const val UNDERFASETT_TROMS_OG_FINNMARK = "6"
const val UNDERFASETT_TRONDELAG = "7"
const val UNDERFASETT_VESTFOLD_OG_TELEMARK = "8"
const val UNDERFASETT_VESTLAND = "9"
const val UNDERFASETT_VEST_VIKEN = "10"
const val UNDERFASETT_OST_VIKEN = "11"

const val TIDSPERIODE_OLDER_THAN_12_MONTHS = 0
const val TIDSPERIODE_LAST_12_MONTHS = 1
const val TIDSPERIODE_LAST_30_DAYS = 2
const val TIDSPERIODE_LAST_7_DAYS = 3